arch:
  - amd64
  - arm64
language: go
dist: xenial
sudo: required
install: true
services:
  - docker
go:
  - 1.13.x
env:
  global:
    - GO_FOR_RELEASE=1.13

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y curl open-iscsi
  - mount
  - cat /proc/filesystems
  - go get -u golang.org/x/lint/golint
  - go env && pwd
  - mkdir -p $HOME/gopath/bin
script:
  - make build
notifications:
  email:
    recipients:
      - kiran.mova@mayadata.io
      - utkarsh.tripathi@mayadata.io
      - vitta@mayadata.io
      - payes.anand@mayadata.io
