#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running tests

PACKAGES="$(find . -name '*.go' | xargs -I{} dirname {} | sort -u | grep -Ev '(.git|.trash-cache|vendor|bin)')"

echo Packages: ${PACKAGES}

if [ ${ARCH} == "linux_arm64" ]
then
	sudo -E env "PATH=$PATH" go test -race -cover -tags="test" ${PACKAGES}
else
	go test -race -cover -tags="test" ${PACKAGES}
fi

